[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11~=2.6.0",
    "cmake",
    "scikit-build",
]

build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
markers = [
    "random: marks tests as random (deselect with '-m \"not random\"')"
]
